name: Android Build

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/android/**'
      - 'ops/ci/android-build.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'apps/android/**'
      - 'ops/ci/android-build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Build (placeholder)
      run: |
        echo "Android build will be implemented when app scaffold is ready"
        # cd apps/android
        # ./gradlew assembleDebug
      continue-on-error: true

